; Rebound GB
; Goony enemy sprite definitions

section "Sprite GFX - Goony",romx
GoonyTiles:

GFX_Goony_Walk1:	incbin	"GFX/Sprites/Goony/Goony.2bpp",$000,64
GFX_Goony_Walk2:	incbin	"GFX/Sprites/Goony/Goony.2bpp",$040,64
GFX_Goony_Walk3:	incbin	"GFX/Sprites/Goony/Goony.2bpp",$080,64
GFX_Goony_Walk4:	incbin	"GFX/Sprites/Goony/Goony.2bpp",$0c0,64
GFX_Goony_Walk5:	incbin	"GFX/Sprites/Goony/Goony.2bpp",$100,64
GFX_Goony_Walk6:	incbin	"GFX/Sprites/Goony/Goony.2bpp",$140,64
GFX_Goony_Walk7:	incbin	"GFX/Sprites/Goony/Goony.2bpp",$180,64
GFX_Goony_Walk8:	incbin	"GFX/Sprites/Goony/Goony.2bpp",$1c0,64
GFX_Goony_Death:	incbin	"GFX/Sprites/Goony/Goony.2bpp",$200,64
